### ISSUE TITLE
Unnecessary dependency for spl-dkms Debian package, 0.6.3-19-086476

### ISSUE THREAD

**Issue by Amitie10g** [zfsonlinux/spl#448]
I noticed that the latest ```spl-dkms``` package version (```0.6.3-19-086476```) depends on ```linux-headers-amd64``` (just a metapackage). This leaves a problem with users (like Me) that use self-compiled kernels and headers, because they're forced to download unwanted header packages.

I have a kernel version 3.18.0 compiled by me and spl-dkms and zfs-dkms were compiled against its headers successfully.

Therefore, this dependency should be removed, or otherwise, changed to ```Suggests```

**Comment by FransUrbo** [comment]
> I have a kernel version 3.18.0 compiled by me and spl-dkms and zfs-dkms were compiled against its headers successfully.
> 
It is there because everyone else is having problem installing it. Suggests
isn't automatically installed…

SInce you're the first (and only) that have had this problem, "I have decided" :)
that as a policy, anyone building they're own kernel, should build ZoL from
GIT as well.

it gives the added benefit of creating a binary module package, so no need
for that dkms crap...

**Comment by Amitie10g** [comment]
I've also think this dependency solves the problem of the most users, and keeping a *dummy* kernel-headers should not be a huge problem.

Therefore, is possible to the kernel-headers to be *suggested* instead of *required*?

**Comment by FransUrbo** [comment]
> Therefore, is possible to the kernel-headers to be suggested instead of required?
> 

No. As I said, normally suggests isn't installed. And people don't read what's right in front of them...

**Comment by Amitie10g** [comment]
Well, you're right. Less problems to most of the users is better.
Finally, I just updated the zfs-dkms and spl-dkms and boots successfully. Noy, update GRUB...
