### ISSUE TITLE
locking in taskq_member() hurts performance on large-scale systems

### ISSUE THREAD

**Issue by dweeezil** [zfsonlinux/spl#500]
On large-scale systems with lots of CPU cores, the locking in ```taskq_member()``` becomes a significant contention point for zios dispatched to the single ```z_wr_iss``` taskq for heavy (high-frequency) IO workloads.  Under illumos, this operation is a single comparison operation whereas under ZoL, it involves taking a lock, iterating through a list and then releasing the lock.

This mainly affects the ```z_wr_iss``` taskq because it's the main zio taskq with a high volume of dispatches but for which only a single taskq is allocated.  Unfortunately, the obvious workaround of something like this:
```
diff --git a/module/zfs/spa.c b/module/zfs/spa.c
index 2e23a34..9480c2b 100644
--- a/module/zfs/spa.c
+++ b/module/zfs/spa.c
@@ -128,7 +128,7 @@ const zio_taskq_info_t zio_taskqs[ZIO_TYPES][ZIO_TASKQ_TYPES] = {
        /* ISSUE        ISSUE_HIGH      INTR            INTR_HIGH */
        { ZTI_ONE,      ZTI_NULL,       ZTI_ONE,        ZTI_NULL }, /* NULL */
        { ZTI_N(8),     ZTI_NULL,       ZTI_P(12, 8),   ZTI_NULL }, /* READ */
-       { ZTI_BATCH,    ZTI_N(5),       ZTI_P(12, 8),   ZTI_N(5) }, /* WRITE */
+       { ZTI_P(4, 10), ZTI_N(5),       ZTI_P(12, 8),   ZTI_N(5) }, /* WRITE */
        { ZTI_P(12, 8), ZTI_NULL,       ZTI_ONE,        ZTI_NULL }, /* FREE */
        { ZTI_ONE,      ZTI_NULL,       ZTI_ONE,        ZTI_NULL }, /* CLAIM */
        { ZTI_ONE,      ZTI_NULL,       ZTI_ONE,        ZTI_NULL }, /* IOCTL */
```
seems to expose other bottlenecks during high-throughput benchmarking and actually reduces performance.  I've not yet discovered why this happens but the above patch definitely reduces the impact of the locking in ```taskq_member()```.

**Comment by behlendorf** [comment]
@dweeezil very interesting.  Not only is `taskq_member()` more expensive under ZoL but we also use it three times in `__zio_execute()` and illumos uses it only once.  This done to avoid stack overruns.  However, since the kernel moved to default 16K stacks it's occurred to me that we could begin wrapping code like this with an `#ifdef` conditional.  Then modern kernels wouldn't need to pay this penalty and older ones would remain stable.  A similar thing should be done for `dump_bytes()`.

We could also look in to optimizing `taskq_member()`.  I'm sure there's a more efficient way to implement this check.

**Comment by tuxoko** [comment]
The zio_taskq_member do list search for every single taskq. No wonder it's very slow and contentious. We can use a hash table to map to the taskq.

**Comment by dweeezil** [comment]
@tuxoko That's kind of what I thought, too, after comparing the SPL implementation with illumos.

**Comment by tuxoko** [comment]
@dweeezil 
https://gist.github.com/tuxoko/45c0686cfe845552e792
I use tsd for storing taskq pointer. The tsd has per hash slot spinlock, so it the contention should be better. Could you try it out and see if things get better?

**Comment by dweeezil** [comment]
@tuxoko I'll give it a try but may not have a chance to get a test set up until this coming weekend.

**Comment by behlendorf** [comment]
@tuxoko regarding https://gist.github.com/tuxoko/45c0686cfe845552e792 it would be great to drop that in a pull request.  Since it look's like we're going to be stuck supporting the tsd interfaces forever I agree we should take advantage of them!

@dweeezil if you do get a change to do any performance testing you may also want to include zfsonlinux/zfs#4059.  It's the long over due 16K stack optimization I alluded to above.

**Comment by dweeezil** [comment]
@behlendorf I'll definitely include your new patch, which looks perfectly reasonable to me at first glance.

**Comment by ryao** [comment]
It is possible to use the ->journal_info pointer in the task_struct to mark whether a thread is a taskq or not. Its state is saved much like interrupt flags when something is using it. All consumers of taskq_member are in the ZIO threads, so there is no way of calling back into code using taskq_member from a Linux function that would cause a runtime failure

**Comment by ryao** [comment]
@behlendorf Pull request #505 has an a simpler solution that replaces taskq_member with a pointer comparison. I have been using this technique in local branches where I had a port of the illumos taskq code without issues. Some quick tests do not reveal any problems, so it is likely that we can use it here.
