### ISSUE TITLE
ia64: Unsupported ISA type

### ISSUE THREAD

**Issue by K1773R** [zfsonlinux/spl#676]
Has the support for ia64 been dropped completely? spl/zfs refuses to build due to the unsupported isa type check in 'lib/libspl/include/sys/isa_defs.h'

**Comment by behlendorf** [comment]
@K1773R support for ia64 was never there in the first place.  It _could_ be added be adding the needed defines to both the spl and zfs isa files.  We haven't done so since we don't have the hardware around to easily test with.  If you do and would like to enable this support please go ahead and open a PR.
